// Main application class, generated by Spring Initializr.
// Must live in the top package so that @SpringBootApplication annotation
// can find all the components.

package welcome;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class WelcomeDemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(WelcomeDemoApplication.class, args);
    }

}
